language: python

# needed for python>=3.7
dist: xenial

python:
  - 3.6
  - 3.7

stages:
  - prep_cache
  - test
  - osx_tests
  - integration_tests
  - deploy

env:
  global:
    - HOMEBREW_NO_INSTALL_CLEANUP=1
    - HOMEBREW_NO_ANALYTICS=1
  matrix:
    - KARTOTHEK_ARROW_VERSION=0.12.1
    - KARTOTHEK_ARROW_VERSION=0.13.0

cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
    - /usr/local/Homebrew
    - python_versions
#
#before_cache:
#  - brew cleanup
#  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
#
#addons:
#  homebrew:
#    packages: pyenv
#    update: true

before_install:
  - ./before_install.sh

install:
  - pip install -r test-requirements-pinned.txt
  - pip install --no-deps dist/*

# If docs break or formatting, linting is off, I'd like to know immediately
before_script:
  - pip freeze
  - pip install pre-commit && pre-commit run -a
  - python setup.py docs

script:
  - pytest

after_success:
  - pip install codecov
  - codecov

matrix:
  include:
    - name: "prep cache"
      stage: prep_cache
      script:
        - mkdir -p ./python_versions
    - name: "OSX + python3.7"
      stage: osx_tests
      os: osx
      language: shell

#      env:
#        - HOMEBREW_NO_INSTALL_CLEANUP=1
#        - HOMEBREW_NO_ANALYTICS=1


#    - name: "OSX + python3.7"
#      os: osx
#      language: shell
#      env:
#        - HOMEBREW_NO_INSTALL_CLEANUP=1
#        - HOMEBREW_NO_ANALYTICS=1
#      cache:
#        directories:
#          - "$HOME/Library/Caches/Homebrew"
#          - /usr/local/Homebrew
#      before_cache:
#        - brew cleanup
#        - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
#      addons:
#        homebrew:
#          update: true
#          packages:
#            - pyenv
    - name: "deploy"
      stage: deploy
      deploy:
        provider: pypi
        user: fjetter
        password:
          secure: pO3DOtJa2xrqRWPUutUpF44veWQ34MoiAHLDXps+g//ZHLMqcdZ4YX2M4eHDUSDA9kqd0kc1Rj0un6mPzcKVq2c5AsceNT4qh0eojlStfqGh4Lr5EsfIs7nsrK+gtpKdvogECHxv+Rz07nFXKPqh2TGuIwiHmSVQ56Mo89S1xGD66mqEJf7MTyIM2vo/n9Bs4nWYapqDWs2ExkVfXfc1oasEyled3PF7NdtBokWhQmFcULBSunh57hFtPOuD4v2WyhAdnBR3ivzDYQS7n9+lOO6cdkdkZy0Agm0+FdP+18GFFcwHAamIPEAspfmI9+h+/3pm5TvUp5pU+lvuUtypp3eYt20AIYjmqUdDj8HHGSYINl9ef4zlQu+ARFWlO/+B8gtWjsBHtaJIq/wsBNsAJjjLZByHZwjzm+NQKTP7z18EtIhNqjIb/v/6Qgapo6BDjbbVajFLtj5esLcAAhg8Hw+wzoNxrOSnALDUiQd0Tro1DnXkl+WrTKtz0pu4h7yKpQiwOS6hv4ltjDyL7gyW+N9O2yAJBH8r6aI1UjyXyAO57v/GXjjF7JOTEnl9lvEufBFwnQYTjcoSo0bupXRELz1ytabk3IP5Z7meoAoA73DdyPYSltZx88SuP7jACZOjkXjOLrJi02V/vz8+bMl+I8M5MvPoTnLY7cn1cjZv4BU=
        on:
          tags: true
        distributions: "sdist bdist_wheel"
        skip_existing: true

#if: os = osx
#cache:
#  directories:
#    - "$HOME/Library/Caches/Homebrew"
#    - /usr/local/Homebrew
#
#before_cache:
#  - brew cleanup
#  - find /usr/local/Homebrew \! -regex ".+\.git.+" -delete
#
#addons:
#  homebrew:
#    packages:
#      - pyenv
#    update: true
