language: python

# needed for python>=3.7
dist: xenial

python:
  - 3.6
  - 3.7

stages:
  - test
  - name: deploy
    if: branch = master

env:
  - KARTOTHEK_ARROW_VERSION=0.12.1
  - KARTOTHEK_ARROW_VERSION=0.13.0

before_install:
  - pip3 install --upgrade pip
  - pip3 install pip-tools
  - ./compile_requirements.sh
  - python3 setup.py bdist_wheel

install:
  - pip3 install -r test-requirements-pinned.txt
  - pip3 install --no-deps dist/*

# If docs break or formatting, linting is off, I'd like to know immediately
before_script:
  - pip3 freeze
  - pip3 install pre-commit && pre-commit run -a
  - python3 setup.py docs

script:
  - python3 -m pytest

after_success:
  - pip3 install codecov
  - codecov

jobs:
  include:
    - stage: test
      name: "OSX"
      os: osx
      language: shell
      addons:
        homebrew:
          # update: true
          packages: python3
        before_install:
          - python3 -m pip install --upgrade virtualenv
          - virtualenv -p python3 --system-site-packages "$HOME/venv"
          - source "$HOME/venv/bin/activate"

    - stage: deploy
      deploy:
        provider: pypi
        user: fjetter
        password:
          secure: pO3DOtJa2xrqRWPUutUpF44veWQ34MoiAHLDXps+g//ZHLMqcdZ4YX2M4eHDUSDA9kqd0kc1Rj0un6mPzcKVq2c5AsceNT4qh0eojlStfqGh4Lr5EsfIs7nsrK+gtpKdvogECHxv+Rz07nFXKPqh2TGuIwiHmSVQ56Mo89S1xGD66mqEJf7MTyIM2vo/n9Bs4nWYapqDWs2ExkVfXfc1oasEyled3PF7NdtBokWhQmFcULBSunh57hFtPOuD4v2WyhAdnBR3ivzDYQS7n9+lOO6cdkdkZy0Agm0+FdP+18GFFcwHAamIPEAspfmI9+h+/3pm5TvUp5pU+lvuUtypp3eYt20AIYjmqUdDj8HHGSYINl9ef4zlQu+ARFWlO/+B8gtWjsBHtaJIq/wsBNsAJjjLZByHZwjzm+NQKTP7z18EtIhNqjIb/v/6Qgapo6BDjbbVajFLtj5esLcAAhg8Hw+wzoNxrOSnALDUiQd0Tro1DnXkl+WrTKtz0pu4h7yKpQiwOS6hv4ltjDyL7gyW+N9O2yAJBH8r6aI1UjyXyAO57v/GXjjF7JOTEnl9lvEufBFwnQYTjcoSo0bupXRELz1ytabk3IP5Z7meoAoA73DdyPYSltZx88SuP7jACZOjkXjOLrJi02V/vz8+bMl+I8M5MvPoTnLY7cn1cjZv4BU=
        on:
          tags: true
        distributions: "sdist bdist_wheel"
        skip_existing: true
